//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cake.Helpers.Tests.Unit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cake.Helpers.Tests.Unit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project Sdk=&quot;Microsoft.NET.Sdk&quot;&gt;
        ///
        ///  &lt;PropertyGroup&gt;
        ///    &lt;TargetFrameworks&gt;net452&lt;/TargetFrameworks&gt;
        ///  &lt;/PropertyGroup&gt;
        ///  
        ///  &lt;ItemGroup&gt;
        ///    &lt;PackageReference Include=&quot;Cake.Core&quot; Version=&quot;0.21.1&quot; /&gt;
        ///		&lt;PackageReference Include=&quot;Cake.Common&quot; Version=&quot;0.21.1&quot; /&gt;
        ///  &lt;/ItemGroup&gt;
        ///
        ///&lt;/Project&gt;.
        /// </summary>
        internal static string DefaultProject1Content {
            get {
                return ResourceManager.GetString("DefaultProject1Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Working/src/Cake.Helpers/Cake.Helpers.csproj.
        /// </summary>
        internal static string DefaultProject1Location {
            get {
                return ResourceManager.GetString("DefaultProject1Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project Sdk=&quot;Microsoft.NET.Sdk&quot;&gt;
        ///
        ///  &lt;PropertyGroup&gt;    
        ///    &lt;TargetFrameworks&gt;net452&lt;/TargetFrameworks&gt;
        ///  &lt;/PropertyGroup&gt;
        ///
        ///  &lt;ItemGroup&gt;
        ///    &lt;PackageReference Include=&quot;Microsoft.NET.Test.Sdk&quot; Version=&quot;15.0.0&quot; /&gt;
        ///    &lt;PackageReference Include=&quot;Moq&quot; Version=&quot;4.7.99&quot; /&gt;
        ///    &lt;PackageReference Include=&quot;MSTest.TestAdapter&quot; Version=&quot;1.1.11&quot; /&gt;
        ///    &lt;PackageReference Include=&quot;MSTest.TestFramework&quot; Version=&quot;1.1.11&quot; /&gt;
        ///    &lt;PackageReference Include=&quot;Cake.Core&quot; Version=&quot;0.21.1&quot; /&gt;
        ///    &lt;PackageReference In [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultProject2Content {
            get {
                return ResourceManager.GetString("DefaultProject2Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Working/test/Cake.Helpers.Tests.Unit/Cake.Helpers.Tests.Unit.csproj.
        /// </summary>
        internal static string DefaultProject2Location {
            get {
                return ResourceManager.GetString("DefaultProject2Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visual Studio Solution File, Format Version 12.00
        ///# Visual Studio 15
        ///VisualStudioVersion = 15.0.26430.16
        ///MinimumVisualStudioVersion = 10.0.40219.1
        ///Project(&quot;{9A19103F-16F7-4668-BE54-9A1E7A4F7556}&quot;) = &quot;Cake.Helpers&quot;, &quot;src\Cake.Helpers\Cake.Helpers.csproj&quot;, &quot;{934540A4-906D-4637-A0B4-F8A662588C6A}&quot;
        ///EndProject
        ///Project(&quot;{9A19103F-16F7-4668-BE54-9A1E7A4F7556}&quot;) = &quot;Cake.Helpers.Tests.Unit&quot;, &quot;test\Cake.Helpers.Tests.Unit\Cake.Helpers.Tests.Unit.csproj&quot;, &quot;{35A3BF7E-DF00-46C8-9EFA-F7804106A24B}&quot;
        ///EndPr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultSlnContent {
            get {
                return ResourceManager.GetString("DefaultSlnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Working/Cake.Helpers.sln.
        /// </summary>
        internal static string DefaultSlnFileLocation {
            get {
                return ResourceManager.GetString("DefaultSlnFileLocation", resourceCulture);
            }
        }
    }
}
